---
title: "Análise Bayesiana para Inferência Causal na COVID-19"
subtitle: "Impacto da Vacinação"
author: "José Elvano Moraes"
date: "12/04/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Dataset* = https://dados.gov.br/dataset/bd-srag-2019

--------


**SRAG 2021** - Banco de Dados de Síndrome Respiratória Aguda Grave
Vigilância de Síndrome Respiratória Aguda Grave (SRAG)
O Ministério da Saúde, por meio da Secretaria de Vigilância em Saúde (SVS), desenvolve a vigilância da Síndrome Respiratória Aguda Grave (SRAG) no Brasil, desde 2009, devido a pandemia de Influenza A(H1N1)pdm09. A partir disso, a vigilância de SRAG foi implantada na rede de vigilância de Influenza e outros vírus respiratórios, que anteriormente atuava apenas com a vigilância sentinela de Síndrome Gripal (SG).

Recentemente (2020), a vigilância da COVID-19, a infecção humana causada pelo novo Coronavírus, que vem causando uma pandemia, foi incorporada na rede de vigilância da Influenza e outros vírus respiratórios.

Esta página tem como finalidade disponibilizar o legado dos banco de dados (BD) epidemiológicos de SRAG, da rede de vigilância da Influenza e outros vírus respiratórios, desde o início da sua implantação (2009) até os dias atuais (2020), com a incorporação da vigilância da COVID-19.

Para mais informações, acessar:

Gripe/Influenza - https://saude.gov.br/saude-de-a-z/gripe

COVID-19 - https://coronavirus.saude.gov.br/

--------

# Nota
Este documento é ainda tão somente experimentação e análise exploratória em fase absolutamente incipiente. Por isso a falta de estrutura, gráficos não explicativos, *typos*, etc

# Inferência da estrutura da Rede Causal usando o Algoritmo **mmhc**

-------

```{r libraries}
suppressPackageStartupMessages(expr = library(tidyverse))
suppressPackageStartupMessages(expr = library(bnlearn))
suppressPackageStartupMessages(expr = library(bnstruct))
suppressPackageStartupMessages(expr = library(readr))
suppressPackageStartupMessages(expr = library(Rgraphviz))
suppressPackageStartupMessages(expr = library(Rmpfr))
```


```{r}
dados <- read_csv("x_to_be_factors.csv", 
    col_types = cols(
        FEBRE = col_factor(levels = c("1", "2", "9")), 
        TOSSE = col_factor(levels = c("1", "2", "9")), 
        GARGANTA = col_factor(levels = c("1", "2", "9")), 
        DISPNEIA = col_factor(levels = c("1", "2", "9")), 
        DESC_RESP = col_factor(levels = c("1", "2", "9")), 
        SATURACAO = col_factor(levels = c("1", "2", "9")), 
        DIARREIA = col_factor(levels = c("1", "2", "9")), 
        VOMITO = col_factor(levels = c("1", "2", "9")), 
        OUTRO_SIN = col_factor(levels = c("1", "2", "9")), 
        HOSPITAL = col_factor(levels = c("1", "2", "9")), 
        EVOLUCAO = col_factor(levels = c("1", "2", "3", "9")), 
        RENAL = col_factor(levels = c("1", "2", "9")), 
        DIABETES = col_factor(levels = c("1", "2", "9")), 
        OBESIDADE = col_factor(levels = c("1", "2", "9")), 
        PERD_OLFT = col_factor(levels = c("1", "2", "9")), 
        PERD_PALA = col_factor(levels = c("1", "2", "9")), 
        VACINA = col_factor(levels = c("1", "2", "9")), 
        CLASSI_FIN = col_factor(levels = c("1", "2", "3", "4", "5"))))
```

# Subconjunto de variáveis
```{r echo=TRUE}
#reselecionar retira a variavel automatica X1
 xx <- select(dados,
            FEBRE,        # 1 = sim, 2 = nao, 9 = ignorado
            TOSSE,        # 1 = sim, 2 = nao, 9 = ignorado
            GARGANTA,     # 1 = sim, 2 = nao, 9 = ignorado
            DISPNEIA,     # 1 = sim, 2 = nao, 9 = ignorado
            DESC_RESP,    # 1 = sim, 2 = nao, 9 = ignorado
            SATURACAO,    # 1 = sim, 2 = nao, 9 = ignorado
            DIARREIA,     # 1 = sim, 2 = nao, 9 = ignorado
            VOMITO,       # 1 = sim, 2 = nao, 9 = ignorado
            OUTRO_SIN,    # 1 = sim, 2 = nao, 9 = ignorado
            #HOSPITAL,     # 1 = sim, 2 = nao, 9 = ignorado
            EVOLUCAO,     # 1 = sim, 2 = nao, 9 = ignorado 
            RENAL,        # 1 = sim, 2 = nao, 9 = ignorado
            DIABETES,     # 1 = sim, 2 = nao, 9 = ignorado
            OBESIDADE,    # 1 = sim, 2 = nao, 9 = ignorado
            PERD_OLFT,    # 1 = sim, 2 = nao, 9 = ignorado
            PERD_PALA,    # 1 = sim, 2 = nao, 9 = ignorado
            VACINA,       # 1 = sim, 2 = nao, 9 = ignorado
            #--------------|------------------------------------------
            CLASSI_FIN)   #| 1 = SRAG por influenza 
                          #| 2 = SRAG por outro virus respiratorio
                          #| 3 = SRAG por outro agente etiologico, qual:
                          #| 4 = SRAG nao especificado 
                          #| 5 = SRAG por COVID-19
            # -------------|------------------------------------------
# dado não pode ser `tible` nas funções de *bnlearn*
x = as.data.frame(xx)
```

```{r echo=TRUE}
# mmhc e mmhc não admitem NA
x_no_na <- na.omit(x)
```

```{r echo=TRUE}
srag_todas <- x_no_na
srag_covid <- x_no_na %>% filter(CLASSI_FIN == 5)
srag_influenza <- x_no_na %>% filter(CLASSI_FIN == 1)
srag_outro_virus_respiratorio <- x_no_na %>% filter(CLASSI_FIN == 2)
srag_outro_agente_etiologico <- x_no_na %>% filter(CLASSI_FIN == 3)
srag_nao_especificada <- x_no_na %>% filter(CLASSI_FIN == 4)
srag_nao_covid <- x_no_na %>% filter(CLASSI_FIN != 5)
```


```{r pressure, echo=TRUE}
suppressWarnings(bn_mmhc <- mmhc(srag_todas))
suppressWarnings(bn_mmhc_srag_covid<- mmhc(srag_covid))
suppressWarnings(bn_mmhc_influenza <- mmhc(srag_influenza))
suppressWarnings(bn_mmhc_srag_outro_virus_respiratorio <- mmhc(srag_outro_virus_respiratorio))
suppressWarnings(bn_mmhc_srag_outro_agente_etiologico <- mmhc(srag_outro_agente_etiologico))
suppressWarnings(bn_mmhc_srag_nao_especificada <- mmhc(srag_nao_especificada))
suppressWarnings(bn_mmhc_srag_nao_covid <- mmhc(srag_nao_covid))



graphviz.plot(bn_mmhc, shape = 'rectangle', main = "Todas causas de SRAG")

graphviz.plot(bn_mmhc_srag_covid, shape = 'rectangle', main = "SRAG por COVID-19")

graphviz.plot(bn_mmhc_influenza, shape = 'rectangle', main = "SRAG por Influenza")

graphviz.plot(bn_mmhc_srag_outro_virus_respiratorio, shape = 'rectangle', main = "SRAG por Outro  Virus Respiratório")

graphviz.plot(bn_mmhc_srag_outro_agente_etiologico, shape = 'rectangle', main = "SRAG por Outros Agentes Etiológicos")

graphviz.plot(bn_mmhc_srag_nao_especificada, shape = 'rectangle', main = "SRAG Não Especificada")

graphviz.plot(bn_mmhc_srag_nao_covid, shape = 'rectangle', main = "TODAS SRAG Não COVID-19")
```

-----------

# Ajustamento da estrutura da rede com os dados

## Descrição estatística da rede para a variável VACINA
```{r echo=TRUE}
fitted_mmhc_bn_srag_covid = bn.fit(bn_mmhc_srag_covid, srag_covid)

fitted_mmhc_bn_srag_covid$VACINA
    
suppressWarnings(bn.fit.barchart(fitted_mmhc_bn_srag_covid$VACINA, xlab = "Probabilidade", ylab = "VACINA SRAG POR COVID-19"))
```