##### veja  linha 162

library(readr)
dados <- read_delim("INFLUD21-05-04-2021.csv", 
                                  ";", escape_double = FALSE,  
                                  trim_ws = TRUE,
                                  col_types = cols(
                                                    DT_NOTIFIC = col_character(),
                                                    SEM_NOT = col_double(),
                                                    DT_SIN_PRI = col_character(),
                                                    SEM_PRI = col_double(),
                                                    SG_UF_NOT = col_character(),
                                                    ID_REGIONA = col_character(),
                                                    CO_REGIONA = col_double(),
                                                    ID_MUNICIP = col_character(),
                                                    CO_MUN_NOT = col_double(),
                                                    ID_UNIDADE = col_character(),
                                                    CO_UNI_NOT = col_double(),
                                                    CS_SEXO = col_character(),
                                                    DT_NASC = col_character(),
                                                    NU_IDADE_N = col_double(),
                                                    TP_IDADE = col_double(),
                                                    COD_IDADE = col_double(),
                                                    CS_GESTANT = col_double(),
                                                    CS_RACA = col_double(),
                                                    CS_ETINIA = col_logical(),
                                                    CS_ESCOL_N = col_double(),
                                                    ID_PAIS = col_character(),
                                                    CO_PAIS = col_double(),
                                                    SG_UF = col_character(),
                                                    ID_RG_RESI = col_character(),
                                                    CO_RG_RESI = col_double(),
                                                    ID_MN_RESI = col_character(),
                                                    CO_MUN_RES = col_double(),
                                                    CS_ZONA = col_double(),
                                                    SURTO_SG = col_double(),
                                                    NOSOCOMIAL = col_double(),
                                                    AVE_SUINO = col_double(),
                                                    FEBRE = col_double(),
                                                    TOSSE = col_double(),
                                                    GARGANTA = col_double(),
                                                    DISPNEIA = col_double(),
                                                    DESC_RESP = col_double(),
                                                    SATURACAO = col_double(),
                                                    DIARREIA = col_double(),
                                                    VOMITO = col_double(),
                                                    OUTRO_SIN = col_double(),
                                                    OUTRO_DES = col_character(),
                                                    PUERPERA = col_double(),
                                                    FATOR_RISC = col_character(),
                                                    CARDIOPATI = col_double(),
                                                    HEMATOLOGI = col_double(),
                                                    SIND_DOWN = col_double(),
                                                    HEPATICA = col_double(),
                                                    ASMA = col_double(),
                                                    DIABETES = col_double(),
                                                    NEUROLOGIC = col_double(),
                                                    PNEUMOPATI = col_double(),
                                                    IMUNODEPRE = col_double(),
                                                    RENAL = col_double(),
                                                    OBESIDADE = col_double(),
                                                    OBES_IMC = col_character(),
                                                    OUT_MORBI = col_double(),
                                                    MORB_DESC = col_character(),
                                                    VACINA = col_double(),
                                                    DT_UT_DOSE = col_character(),
                                                    MAE_VAC = col_double(),
                                                    DT_VAC_MAE = col_logical(),
                                                    M_AMAMENTA = col_double(),
                                                    DT_DOSEUNI = col_logical(),
                                                    DT_1_DOSE = col_logical(),
                                                    DT_2_DOSE = col_logical(),
                                                    ANTIVIRAL = col_double(),
                                                    TP_ANTIVIR = col_double(),
                                                    OUT_ANTIV = col_character(),
                                                    DT_ANTIVIR = col_character(),
                                                    HOSPITAL = col_double(),
                                                    DT_INTERNA = col_character(),
                                                    SG_UF_INTE = col_character(),
                                                    ID_RG_INTE = col_character(),
                                                    CO_RG_INTE = col_double(),
                                                    ID_MN_INTE = col_character(),
                                                    CO_MU_INTE = col_double(),
                                                    UTI = col_double(),
                                                    DT_ENTUTI = col_character(),
                                                    DT_SAIDUTI = col_character(),
                                                    SUPORT_VEN = col_double(),
                                                    RAIOX_RES = col_double(),
                                                    RAIOX_OUT = col_character(),
                                                    DT_RAIOX = col_character(),
                                                    AMOSTRA = col_double(),
                                                    DT_COLETA = col_character(),
                                                    TP_AMOSTRA = col_double(),
                                                    OUT_AMOST = col_character(),
                                                    PCR_RESUL = col_double(),
                                                    DT_PCR = col_character(),
                                                    POS_PCRFLU = col_double(),
                                                    TP_FLU_PCR = col_logical(),
                                                    PCR_FLUASU = col_logical(),
                                                    FLUASU_OUT = col_logical(),
                                                    PCR_FLUBLI = col_logical(),
                                                    FLUBLI_OUT = col_logical(),
                                                    POS_PCROUT = col_double(),
                                                    PCR_VSR = col_double(),
                                                    PCR_PARA1 = col_logical(),
                                                    PCR_PARA2 = col_logical(),
                                                    PCR_PARA3 = col_logical(),
                                                    PCR_PARA4 = col_logical(),
                                                    PCR_ADENO = col_logical(),
                                                    PCR_METAP = col_logical(),
                                                    PCR_BOCA = col_logical(),
                                                    PCR_RINO = col_double(),
                                                    PCR_OUTRO = col_double(),
                                                    DS_PCR_OUT = col_character(),
                                                    CLASSI_FIN = col_double(),
                                                    CLASSI_OUT = col_character(),
                                                    CRITERIO = col_double(),
                                                    EVOLUCAO = col_double(),
                                                    DT_EVOLUCA = col_character(),
                                                    DT_ENCERRA = col_character(),
                                                    DT_DIGITA = col_character(),
                                                    HISTO_VGM = col_double(),
                                                    PAIS_VGM = col_character(),
                                                    CO_PS_VGM = col_double(),
                                                    LO_PS_VGM = col_character(),
                                                    DT_VGM = col_character(),
                                                    DT_RT_VGM = col_character(),
                                                    PCR_SARS2 = col_double(),
                                                    PAC_COCBO = col_character(),
                                                    PAC_DSCBO = col_character(),
                                                    OUT_ANIM = col_logical(),
                                                    DOR_ABD = col_double(),
                                                    FADIGA = col_double(),
                                                    PERD_OLFT = col_double(),
                                                    PERD_PALA = col_double(),
                                                    TOMO_RES = col_double(),
                                                    TOMO_OUT = col_character(),
                                                    DT_TOMO = col_character(),
                                                    TP_TES_AN = col_double(),
                                                    DT_RES_AN = col_character(),
                                                    RES_AN = col_double(),
                                                    POS_AN_FLU = col_double(),
                                                    TP_FLU_AN = col_logical(),
                                                    POS_AN_OUT = col_double(),
                                                    AN_SARS2 = col_double(),
                                                    AN_VSR = col_logical(),
                                                    AN_PARA1 = col_logical(),
                                                    AN_PARA2 = col_logical(),
                                                    AN_PARA3 = col_logical(),
                                                    AN_ADENO = col_logical(),
                                                    AN_OUTRO = col_logical(),
                                                    DS_AN_OUT = col_logical(),
                                                    TP_AM_SOR = col_double(),
                                                    SOR_OUT = col_character(),
                                                    DT_CO_SOR = col_character(),
                                                    TP_SOR = col_double(),
                                                    OUT_SOR = col_character(),
                                                    DT_RES = col_character(),
                                                    RES_IGG = col_double(),
                                                    RES_IGM = col_double(),
                                                    RES_IGA = col_double()
                      )
)

#DT_NOTIFIC = col_character(),# DD/MM/AAAA,
#SEM_NOT = col_character(), #semana notificacao
#DT_SIN_PRI = col_factor(levels = c("1", "2", "9")),
#SEM_PRI = col_factor(levels = c("1", "2", "9")),
#SG_UF_NOT = col_factor(levels = c("1", "2", "9")),
#ID_REGIONA = col_factor(levels = c("1", "2", "9")),
#CO_REGIONA = col_factor(levels = c("1", "2", "9")),
#ID_MUNICIP = col_factor(levels = c("1", "2", "9")),
#CO_MUN_NOT = col_factor(levels = c("1", "2", "9")),
#ID_UNIDADE = col_factor(levels = c("1", "2", "9")),
#CO_UNI_NOT = col_factor(levels = c("1", "2", "9")),
#CS_SEXO = col_factor(levels = c("1", "2", "9")),
#DT_NASC = col_factor(levels = c("1", "2", "9")),
#NU_IDADE_N = col_factor(levels = c("1", "2", "9")),
#TP_IDADE = col_factor(levels = c("1", "2", "9")),
#COD_IDADE = col_factor(levels = c("1", "2", "9")),
#CS_GESTANT = col_factor(levels = c("1", "2", "9")),
#CS_RACA = col_factor(levels = c("1", "2", "9")),
#CS_ETINIA = col_factor(levels = c("1", "2", "9")),
#CS_ESCOL_N = col_factor(levels = c("1", "2", "9")),
#ID_PAIS = col_factor(levels = c("1", "2", "9")),
#CO_PAIS = col_factor(levels = c("1", "2", "9")),
#SG_UF = col_factor(levels = c("1", "2", "9")),
#ID_RG_RESI = col_factor(levels = c("1", "2", "9")),
#CO_RG_RESI = col_factor(levels = c("1", "2", "9")),
#ID_MN_RESI = col_factor(levels = c("1", "2", "9")),
#CO_MUN_RES = col_factor(levels = c("1", "2", "9")),
#CS_ZONA = col_factor(levels = c("1", "2", "9")),
#SURTO_SG = col_factor(levels = c("1", "2", "9")),
#NOSOCOMIAL = col_factor(levels = c("1", "2", "9")),
#AVE_SUINO = col_factor(levels = c("1", "2", "9")),
#FEBRE = col_factor(levels = c("1", "2", "9")),
#TOSSE = col_factor(levels = c("1", "2", "9")),
#GARGANTA = col_factor(levels = c("1", "2", "9")),
#DISPNEIA = col_factor(levels = c("1", "2", "9")),
#DESC_RESP = col_factor(levels = c("1", "2", "9")),
#SATURACAO = col_factor(levels = c("1", "2", "9")),
#DIARREIA = col_factor(levels = c("1", "2", "9")),
#VOMITO = col_factor(levels = c("1", "2", "9")),
#OUTRO_SIN = col_factor(levels = c("1", "2", "9")),
#OUTRO_DES = col_factor(levels = c("1", "2", "9")),
#PUERPERA = col_factor(levels = c("1", "2", "9")),
#FATOR_RISC = col_factor(levels = c("1", "2", "9")),
#CARDIOPATI = col_factor(levels = c("1", "2", "9")),
#HEMATOLOGI = col_factor(levels = c("1", "2", "9")),
#SIND_DOWN = col_factor(levels = c("1", "2", "9")),
#HEPATICA = col_factor(levels = c("1", "2", "9")),
#ASMA = col_factor(levels = c("1", "2", "9")),
#DIABETES = col_factor(levels = c("1", "2", "9")),
#NEUROLOGIC = col_factor(levels = c("1", "2", "9")),
#PNEUMOPATI = col_factor(levels = c("1", "2", "9")),
#IMUNODEPRE = col_factor(levels = c("1", "2", "9")),
#RENAL = col_factor(levels = c("1", "2", "9")),
#OBESIDADE = col_factor(levels = c("1", "2", "9")),
#OBES_IMC = col_factor(levels = c("1", "2", "9")),
#OUT_MORBI = col_factor(levels = c("1", "2", "9")),
#MORB_DESC = col_factor(levels = c("1", "2", "9")),
#VACINA = col_factor(levels = c("1", "2", "9")),
#DT_UT_DOSE = col_factor(levels = c("1", "2", "9")),
#MAE_VAC = col_factor(levels = c("1", "2", "9")),
#DT_VAC_MAE = col_factor(levels = c("1", "2", "9")),
#M_AMAMENTA = col_factor(levels = c("1", "2", "9")),
#DT_DOSEUNI = col_factor(levels = c("1", "2", "9")),
#DT_1_DOSE = col_factor(levels = c("1", "2", "9")),
#DT_2_DOSE = col_factor(levels = c("1", "2", "9")),
#ANTIVIRAL = col_factor(levels = c("1", "2", "9")),
#TP_ANTIVIR = col_factor(levels = c("1", "2", "9")),
#OUT_ANTIV = col_factor(levels = c("1", "2", "9")),
#DT_ANTIVIR = col_factor(levels = c("1", "2", "9")),
#HOSPITAL = col_factor(levels = c("1", "2", "9")),
#DT_INTERNA = col_factor(levels = c("1", "2", "9")),
#SG_UF_INTE = col_factor(levels = c("1", "2", "9")),
#ID_RG_INTE = col_factor(levels = c("1", "2", "9")),
#CO_RG_INTE = col_factor(levels = c("1", "2", "9")),
#ID_MN_INTE = col_factor(levels = c("1", "2", "9")),
#CO_MU_INTE = col_factor(levels = c("1", "2", "9")),
#UTI = col_factor(levels = c("1", "2", "9")),
#DT_ENTUTI = col_factor(levels = c("1", "2", "9")),
#DT_SAIDUTI = col_factor(levels = c("1", "2", "9")),
#SUPORT_VEN = col_factor(levels = c("1", "2", "9")),
#RAIOX_RES = col_factor(levels = c("1", "2", "9")),
#RAIOX_OUT = col_factor(levels = c("1", "2", "9")),
#DT_RAIOX = col_factor(levels = c("1", "2", "9")),
#AMOSTRA = col_factor(levels = c("1", "2", "9")),
#DT_COLETA = col_factor(levels = c("1", "2", "9")),
#TP_AMOSTRA = col_factor(levels = c("1", "2", "9")),
#OUT_AMOST = col_factor(levels = c("1", "2", "9")),
#PCR_RESUL = col_factor(levels = c("1", "2", "9")),
#DT_PCR = col_factor(levels = c("1", "2", "9")),
#POS_PCRFLU = col_factor(levels = c("1", "2", "9")),
#TP_FLU_PCR = col_factor(levels = c("1", "2", "9")),
#PCR_FLUASU = col_factor(levels = c("1", "2", "9")),
#FLUASU_OUT = col_factor(levels = c("1", "2", "9")),
#PCR_FLUBLI = col_factor(levels = c("1", "2", "9")),
#FLUBLI_OUT = col_factor(levels = c("1", "2", "9")),
#POS_PCROUT = col_factor(levels = c("1", "2", "9")),
#PCR_VSR = col_factor(levels = c("1", "2", "9")),
#PCR_PARA1 = col_factor(levels = c("1", "2", "9")),
#PCR_PARA2 = col_factor(levels = c("1", "2", "9")),
#PCR_PARA3 = col_factor(levels = c("1", "2", "9")),
#PCR_PARA4 = col_factor(levels = c("1", "2", "9")),
#PCR_ADENO = col_factor(levels = c("1", "2", "9")),
#PCR_METAP = col_factor(levels = c("1", "2", "9")),
#PCR_BOCA = col_factor(levels = c("1", "2", "9")),
#PCR_RINO = col_factor(levels = c("1", "2", "9")),
#PCR_OUTRO = col_factor(levels = c("1", "2", "9")),
#DS_PCR_OUT = col_factor(levels = c("1", "2", "9")),
#CLASSI_FIN = col_factor(levels = c("1", "2", "9")),
#CLASSI_OUT = col_factor(levels = c("1", "2", "9")),
#CRITERIO = col_factor(levels = c("1", "2", "9")),
#EVOLUCAO = col_factor(levels = c("1", "2", "9")),
#DT_EVOLUCA = col_factor(levels = c("1", "2", "9")),
#DT_ENCERRA = col_factor(levels = c("1", "2", "9")),
#DT_DIGITA = col_factor(levels = c("1", "2", "9")),
#HISTO_VGM = col_factor(levels = c("1", "2", "9")),
#PAIS_VGM = col_factor(levels = c("1", "2", "9")),
#CO_PS_VGM = col_factor(levels = c("1", "2", "9")),
#LO_PS_VGM = col_factor(levels = c("1", "2", "9")),
#DT_VGM = col_factor(levels = c("1", "2", "9")),
#DT_RT_VGM = col_factor(levels = c("1", "2", "9")),
#PCR_SARS2 = col_factor(levels = c("1", "2", "9")),
#PAC_COCBO = col_factor(levels = c("1", "2", "9")),
#PAC_DSCBO = col_factor(levels = c("1", "2", "9")),
#OUT_ANIM = col_factor(levels = c("1", "2", "9")),
#DOR_ABD = col_factor(levels = c("1", "2", "9")),
#FADIGA = col_factor(levels = c("1", "2", "9")),
#PERD_OLFT = col_factor(levels = c("1", "2", "9")),
#PERD_PALA = col_factor(levels = c("1", "2", "9")),
#TOMO_RES = col_factor(levels = c("1", "2", "9")),
#TOMO_OUT = col_factor(levels = c("1", "2", "9")),
#DT_TOMO = col_factor(levels = c("1", "2", "9")),
#TP_TES_AN = col_factor(levels = c("1", "2", "9")),
#DT_RES_AN = col_factor(levels = c("1", "2", "9")),
#RES_AN = col_factor(levels = c("1", "2", "9")),
#POS_AN_FLU = col_factor(levels = c("1", "2", "9")),
#TP_FLU_AN = col_factor(levels = c("1", "2", "9")),
#POS_AN_OUT = col_factor(levels = c("1", "2", "9")),
#AN_SARS2 = col_factor(levels = c("1", "2", "9")),
#AN_VSR = col_factor(levels = c("1", "2", "9")),
#AN_PARA1 = col_factor(levels = c("1", "2", "9")),
#AN_PARA2 = col_factor(levels = c("1", "2", "9")),
#AN_PARA3 = col_factor(levels = c("1", "2", "9")),
#AN_ADENO = col_factor(levels = c("1", "2", "9")),
#AN_OUTRO = col_factor(levels = c("1", "2", "9")),
#DS_AN_OUT = col_factor(levels = c("1", "2", "9")),
#TP_AM_SOR = col_factor(levels = c("1", "2", "9")),
#SOR_OUT = col_factor(levels = c("1", "2", "9")),
#DT_CO_SOR = col_factor(levels = c("1", "2", "9")),
#TP_SOR = col_factor(levels = c("1", "2", "9")),
#OUT_SOR = col_factor(levels = c("1", "2", "9")),
#DT_RES = col_factor(levels = c("1", "2", "9")),
#RES_IGG = col_factor(levels = c("1", "2", "9")),
#RES_IGM = col_factor(levels = c("1", "2", "9")),
#RES_IGA = col_factor(levels = c("1", "2", "9"))
#